Pattykev pollingus 1
nyx-ei/pollingus pull request #8
Opened 2022-11-16 21:00 UTC by Pattykev

2022-11-16 23:12 UTC, SanAlexis requested changes
# Appréciation générale
Très bon début, il manque quelques éléments cependant:
* les échelles de Likert;
* les coding questions (tu pouvais très bien utilisé la puissance de Markdown pour interpréter le code);
* les questions aléatoires;
* etc.
*
Pour avoir une idée de ce qu'il manque, tu peux regarder [l'epic](https://github.com/nyx-ei/pollingus/milestone/1).
# Suggestions
Fais une PR par type de questions, pour pouvoir livrer plus régulièrement et surtout des portions plus faciles à reviewer.

2022-11-16 23:12 UTC, SanAlexis commented on markdown-form.md
> +<label for="oui">
<label> trop complexe. Je suggère d'utiliser quelque chose déjà propre au Markdown à la place.

2022-11-16 23:12 UTC, SanAlexis commented on markdown-form.md
> +- [ ] ```<script src="jsf.js"  type="text/javascript"> ```
Excellente approche, mais il faut épurer un peu ça.

2022-11-16 23:12 UTC, SanAlexis commented on markdown-form.md
> +<label>
Même remarque qu'avant.

2022-11-16 23:12 UTC, SanAlexis commented on form/markdown-syntax.md
> +[| radiolist |] intitulé question
N'utilises pas de nom consacré mais des signes que Markdown propose déjà.

2022-11-16 23:12 UTC, SanAlexis commented on form/markdown-syntax.md
> +~ valeur1
Excellent!

2022-11-16 23:12 UTC, SanAlexis commented on form/markdown-syntax.md
> +[| submit |] Soumettre
Pas besoin. C'est un descriptif du formulaire pas un formulaire en soi. Tu vas implémenter le INPUT avec ton webhook.

2022-11-17 21:45 UTC, Pattykev commented on form/markdown-syntax.md
> +[| submit |] Soumettre
ok

2022-11-17 21:46 UTC, Pattykev commented on markdown-form.md
> +<label for="oui">
fait

2022-11-17 21:46 UTC, Pattykev commented on markdown-form.md
> +- [ ] ```<script src="jsf.js"  type="text/javascript"> ```
ok

2022-11-17 21:46 UTC, Pattykev commented on markdown-form.md
> +<label>
ok

2022-11-17 21:47 UTC, Pattykev commented on form/markdown-syntax.md
> +[| radiolist |] intitulé question
ok

2022-11-19 14:45 UTC, SanAlexis approved these changes
Bon travail. On pourra améliorer mais là on a un bon début.

2022-11-19 14:46 UTC, merged

2022-11-19 14:52 UTC, SanAlexis commented
# Suggestions
* Rename the FORM folder to ensure that it's significant for users.
* Create a documentation for the syntax and locate it at the root of the FORM folder.